#pragma once
#include <cstdio>

#ifndef ERR_NOERROR
#define ERR_NOERROR 0
#endif // !ERR_NOERROR

enum MANAGEMENT_ERRORS
{
	ERR_ERROR = 1,
	PARSE_COMMAND_LINE,
	PARSE_COMMAND_LINE_MAN,
	DIRLIST_FAIL,
	ERR_FILE_OF_INTEREST_DOES_NOT_EXIST_SET_FILE_BUFFER, //
	ERR_FOPEN_SET_FILE_BUFFER_COULD_NOT_OPEN_FILE, //
	ERR_FILE_OF_INTEREST_DOES_NOT_EXIST_GET_BUFFER_SIZE, //
	ERR_FILE_OF_INTEREST_BUFFER_SIZE_BUFFER_TOO_SMALL, //
	ERR_SPLIT_STRING_SEPARATE_SUBS,

	PARSECOMMANDLINE_COLUMNNUMBER_GPDS = 20, //Command Line GPDS
	PARSECOMMANDLINE_BLASTEXTENSION_GPDS,
	PARSECOMMANDLINE_FASTAQUERY_GPDS,
	PARSECOMMANDLINE_GENESPATH_GPDS,
	PARSECOMMANDLINE_BLASTFILE_GPDS,
	PARSECOMMANDLINE_OUTPUTPATH_GPDS,
	PARSECOMMANDLINE_STRAINNAME_GPDS,
	PARSECOMMANDLINE_DECONTAMINATIONLIST_GPDS,
	PARSECOMMANDLINE_STRICTDECONTAMINATION_GPDS,
	PARSECOMMANDLINE_KEGGMATRIX_GPDS,
	PARSECOMMANDLINE_KEGGBOOL_GPDS,
	PARSECOMMANDLINE_GENEMAPSPATH_GPDS,
	PARSECOMMANDLINE_GENEMAPSBOOL_GPDS,

	PARSECOMMANDLINE_FASTADIR_OSG = 40, //Command Line OSG
	PARSECOMMANDLINE_ORTHOGROUPDIR_OSG,
	PARSECOMMANDLINE_OUTPUTDIR_OSG,
	PARSECOMMANDLINE_TAXONOMICGROUPFILE_OSG,
	PARSECOMMANDLINE_TAXONOMICTHRESHOLD_OSG,
	PARSECOMMANDLINE_TAXONOMICTHRESHOLD_TOOLOW_OSG,
	PARSECOMMANDLINE_PHYLOPYPRUNERFORMAT_OSG,
	PARSECOMMANDLINE_SUMMARYPATH_OSG,
	PARSECOMMANDLINE_BOOLSUMMARY_OSG,
	PARSECOMMANDLINE_BOOLSKIPTAXONOMICHEADER_OSG,
	PARSECOMMANDLINE_BOOLTAXGROUPFILTER_OSG,
	PARSECOMMANDLINE_BOOLCONCATENATE_HOGS_OSG,
	PARSECOMMANDLINE_BOOLSTRAINONLY_SCPT,

	PARSECOMMANDLINE_TREEFORMAT_APPPF = 60, //Command Line APPPF
	PARSECOMMANDLINE_TREEDIR_APPPF,
	PARSECOMMANDLINE_TAXONOMICGROUPFILE_APPPF,
	PARSECOMMANDLINE_OUTPUTFOLDER_APPPF,
	PARSECOMMANDLINE_BOOLMOVEMAFFTFILE_APPPF,
	PARSECOMMANDLINE_MOVEMAFFTFIELPATH_APPPF,

	PARSECOMMANDLINE_FASTADIR_FPPPR = 80, //Command Line FPPPR
	PARSECOMMANDLINE_OUTPUTDIR_FPPPR,
	PARSECOMMANDLINE_TAXONOMICGROUPFILE_FPPPR,
	PARSECOMMANDLINE_TAXONOMICTHRESHOLD_FPPPR,
	PARSECOMMANDLINE_TAXONOMICTHRESHOLD_TOOLOW_FPPPR,
	PARSECOMMANDLINE_SUMMARYPATH_FPPPR,
	PARSECOMMANDLINE_BOOLSUMMARY_FPPPR,
	PARSECOMMANDLINE_BOOLNOHEADER_FPPPR,
	PARSECOMMANDLINE_BOOLNOGAP_FPPPR,

	PARSECOMMANDLINE_FASTADIR_RFBS = 100, //Command line RFBS
	PARSECOMMANDLINE_HEADERFILE_RFBS,
	PARSECOMMANDLINE_OUTPUTDIR_RFBS,
	PARSECOMMANDLINE_BOOLPHYLOPYPRUNERFORMAT_RFBS,

	PARSECOMMANDLINE_INPUTFOLDER_RASFAF = 120, //Command line RASFAF
	PARSECOMMANDLINE_OUTPUTFOLDER_RASFAF,
	PARSECOMMANDLINE_JOBNUMBER_TOO_LOW_RASFAF,
	PARSECOMMANDLINE_JOBNUMBER_INCORRECT_RASFAF,
	PARSECOMMANDLINE_JOBWAITINGTIME_TOO_LOW_RASFAF,
	PARSECOMMANDLINE_JOBWAITINGTIME_INCORRECT_RASFAF,
	PARSECOMMANDLINE_BOOLISSLURM_RASFAF,
	PARSECOMMANDLINE_BOOLISCONDOR_RASFAF,
	PARSECOMMANDLINE_BOOLISSINGLECORE_RASFAF,
	PARSECOMMANDLINE_JOBLIMIT_RASFAF,

	PARSECOMMANDLINE_FASTAFILE_ONE_COGS = 140, //Command line COGS
	PARSECOMMANDLINE_FASTAFILE_TWO_COGS,
	PARSECOMMANDLINE_FASTAFILE_BASE_COGS,
	PARSECOMMANDLINE_ORTHOGROUPDIR_COGS,
	PARSECOMMANDLINE_OUTPUTDIR_COGS,
	PARSECOMMANDLINE_PHYLOPYPRUNER_FORMAT_COGS,
	PARSECOMMANDLINE_PPPINPUTGRAB_COGS,
	PARSECOMMANDLINE_PPPINPUTDIRONE_COGS,
	PARSECOMMANDLINE_PPPINPUTDIRTWO_COGS,

	PARSECOMMANDLINE_FASTA_TRINITY_DEMC = 160, //Commandl ine DEMC
	PARSECOMMANDLINE_FASTA_PROTEIN_DEMC,
	PARSECOMMANDLINE_TRINOTATE_REPORT_DEMC,
	PARSECOMMANDLINE_DIFFERENTIAL_MATRIX_DEMC,
	PARSECOMMANDLINE_INFERNAL_DEMC,
	PARSECOMMANDLINE_COLUMNS_TO_PARSE_DEMC,
	PARSECOMMANDLINE_BOOL_COLUMNS_DEMC,
	PARSECOMMANDLINE_OUTPUT_FOLDER_DEMC,
	PARSECOMMANDLINE_PREFIX_DEMC,
	PARSECOMMANDLINE_BOOL_FASTA_FILTER_DEMC,

	PARSECOMMANDLINE_KEGGMATRIX_KEGGCOUNTER = 180, //Command line KEGGCounter
	PARSECOMMANDLINE_KEGGDESCRIPTION_KEGGCOUNTER,
	PARSECOMMANDLINE_BOOL_PREFIXTAG_KEGGCOUNTER,
	PARSECOMMANDLINE_PREFIXTAG_KEGGCOUNTER,
	PARSECOMMANDLINE_THRESHOLD_DE_KEGGCOUNTER,
	PARSECOMMANDLINE_THRESHOLD_HITS,
	PARSECOMMANDLINE_THRESHOLD_SETSAVAILABLE,
	PARSECOMMANDLINE_OUTPUT_FOLDER_KEGGCOUNTER,
	PARSECOMMANDLINE_OUTPUT_PREFIX_KEGGCOUNTER,

	PARSECOMMANDLINE_FASTAPATH_BAVA = 200, //command line BAVA (Blast ALL Vs ALL)
	PARSECOMMANDLINE_BLASTDIR_BAVA,
	PARSECOMMANDLINE_OUTPUTDIR_BAVA,
	PARSECOMMANDLINE_OUTPUTPREFIX_BAVA,
	PARSECOMMANDLINE_EVALUETHRESHOLD_BAVA,
	PARSECOMMANDLINE_PERCENTAGETHRESHOLD_BAVA,
	PARSECOMANDLINE_STRAINAMECONVERSION_BAVA,
	PARSECOMMANDLINE_BOOL_MMSEQS_BAVA,

	PARSECOMMANDLINE_PARTITIONFILE_CLCHECK = 220, //Command line CLCHECK
	PARSECOMMANDLINE_CLIPKITFILE_CLCHECK,
	PARSECOMMANDLINE_OUTPUTDIR_CLCHECK,

	PARSECOMMANDLINE_INPUTFOLDER_MIAF = 240, //Command line MIAF
	PARSECOMMANDLINE_OUTPUTFOLDER_MIAF,
	PARSECOMMANDLINE_MAFFTPATH_MIAF,
	PARSECOMMANDLINE_IQTREEPATH_MIAF,
	PARSECOMMANDLINE_SCRIPTPATH_MIAF,
	PARSECOMMANDLINE_SYSTEMTYPE_MIAF,
	PARSECOMMANDLINE_CPULIMIT_MIAF,
	PARSECOMMANDLINE_IQTHREADLIMIT_MIAF,
	PARSECOMMANDLINE_JOBTIMELIMIT_MIAF,
	PARSECOMMANDLINE_BOOLPREQUAL_MIAF,
	PARSECOMMANDLINE_BOOLPREQUAL_IQTREE_MIAF,
	PARSECOMMANDLINE_APPPFPATH_MIAF,
	PARSECOMMANDLINE_BOOL_APPPF_MIAF,
	PARSECOMMANDLINE_TAXONOMICGROUPFILE_MIAF,

	PARSECOMMANDLINE_INPUTFOLDER_FFRBOL = 260, //Command line FFRBOL
	PARSECOMMANDLINE_OUTPUTFOLDER_FFRBOL,
	PARSECOMMANDLINE_MINLENGHT_FFRBOL,
	PARSECOMMANDLINE_MAXLENGTH_FFRBOL,

	PARSECOMMANDLINE_PROTEINNAME_CHANGE_GTVO = 280,
	PARSECOMMANDLINE_COGS_PPP_GTVO,
	PARSECOMMANDLINE_COGS_FPPP_GTVO,
	PARSECOMMANDLINE_ORTHOGROUP_GTVO,
	PARSECOMMANDLINE_OUTPUTFOLDER_GTVO,
	PARSECOMMANDLINE_TAXONOMICGROUP_GTVO,
	PARSECOMMANDLINE_TPM_FOLDER_GTVO,
	PARSECOMMANDLINE_PREFIX_OUTPUT_GTVO,
	PARSECOMMANDLINE_BOOL_PREFIX_GTVO,


	PROPERTYBAG_GETCOLUMNNUMBER_GPDS = 500, //PropertyBag GPDS
	PROPERTYBAG_GETBLASTEXTENSION_GPDS,
	PROPERTYBAG_GETFASTAQUERY_GPDS,
	PROPERTYBAG_GETGENESPATH_GPDS,
	PROPERTYBAG_GETBLASTFILE_GPDS,
	PROPERTYBAG_GETOUTPUTPATH_GPDS,
	PROPERTYBAG_GETSTRAIN_NAME_GPDS,
	PROPERTYBAG_GETSTRICTDECONTAMINATION_GPDS,
	PROPERTYBAG_GETKEGGMATRIX_GPDS,
	PROPERTYBAG_GETKEGGBOOL_GPDS,
	PROPERTYBAG_GETGENEMAPPATH_GPDS,
	PROPERTYBAG_GENEMAPSBOOL_GPDS,

	PROPERTYBAG_GETFASTADIR_OSG = 520, // PropertyBag OSG
	PROPERTYBAG_ORTHOGROUPDIR_OSG,
	PROPERTYBAG_OUTPUTDIR_OSG,
	PROPERTYBAG_TAXONOMICGROUPFILE_OSG,
	PROPERTYBAG_TAXONOMICTHRESHOLD_OSG,
	PROPERTYBAG_PHYLOPYPRUNERFORMAT_OSG,
	PROPERTYBAG_SETTAXONOMICGROUPSIZE_VECTOR_OSG,
	PROPERTYBAG_GETTAXONOMICGROUPSIZE_VECTOR_OSG,
	PROPERTYBAG_GET_SUMMARYPATH_OSG,
	PROPERTYBAG_GET_BOOLSUMMARY_OSG,
	PROPERTYBAG_GET_BOOLTAXONOMICSKIP_OSG,
	PROPERTYBAG_GET_BOOLTAXGROUPFILTER_OSG,
	PROPERTYBAG_GET_BOOLCONCATENATE_HOGS_OSG,
	PROPERTYBAG_GETBOOLSTRAINONLY_SCPT,

	PROPERTYBAG_GETTREEFORMAT_APPPF = 540, //PropertyBag APPPF
	PROPERTYBAG_SETTREEFORMAT_APPPF,
	PROPERTYBAG_GETTREEDIRPATH_APPPF,
	PROPERTYBAG_GETTAXONOMICGROUPFILE_APPPF,
	PROPERTYBAG_GETOUTPUTDIR_APPPF,
	PROPERTYBAG_GET_BOOLMOVEMAFFTFILE_APPPF,
	PROPERTYBAG_GETMOVEMAFFTFILEPATH_APPPF,

	PROPERTYBAG_GETFASTADIR_FPPPR = 560, // PropertyBag FPPPR
	PROPERTYBAG_OUTPUTDIR_FPPPR,
	PROPERTYBAG_TAXONOMICGROUPFILE_FPPPR,
	PROPERTYBAG_TAXONOMICTHRESHOLD_FPPPR,
	PROPERTYBAG_SETTAXONOMICGROUPSIZE_VECTOR_FPPPR,
	PROPERTYBAG_GETTAXONOMICGROUPSIZE_VECTOR_FPPPR,
	PROPERTYBAG_GET_SUMMARYPATH_FPPPR,
	PROPERTYBAG_GET_BOOLSUMMARY_FPPPR,
	PROPERTYBAG_GET_BOOLNOHEADER_FPPPR,
	PROPERTYBAG_GET_BOOLNOGAPS_FPPPR,

	PROPERTYBAG_GETFASTADIR_RFBS = 580, //PropertyBag RFBS
	PROPERTYBAG_GETHEADERFILE_RFBS,
	PROPERTYBAG_GETOUTPUTDIR_RFBS,
	PROPERTYBAG_GETBOOLPHYLOPYPRUNERFORMAT_RFBS,

	PROPERTYBAG_GETINPUTFOLDERSCRIPT_RASFAF = 600, //Propertybag RASFAF
	PROPERTYBAG_GETOUTPUTFOLDERSCRIPT_RASFAF,
	PROPERTYBAG_GETJOBLIMITNUMBER_RASFAF,
	PROPERTYBAG_GETJOBWAITING_TIME_RASFAF,
	PROPERTYBAG_GETBOOLSLURM_RASFAF,
	PROPERTYBAG_GETBOOLCONDOR_RASFAF,
	PROPERTYBAG_GETBOOLSINGLECORE_RASFAF,
	PROPERTYBAG_GETJOBTIMELIMIT_RASFAF,

	PROPERTYBAG_FASTAFILE_ONE_COGS = 620, //Propertybag COGS
	PROPERTYBAG_FASTAFILE_TWO_COGS,
	PROPERTYBAG_FASTAFILE_BASE_COGS,
	PROPERTYBAG_ORTHOGROUPDIR_COGS,
	PROPERTYBAG_OUTPUTDIR_COGS,
	PROPERTYBAG_PHYLOPYPRUNER_FORMAT_COGS,
	PROPERTYBAG_PPPINPUTGRAB_COGS,
	PROPERTYBAG_PPPINPUTDIRONE_COGS,
	PROPERTYBAG_PPPINPUTDIRTWO_COGS,

	PROPERTYBAG_FASTA_TRINITY_DEMC = 640, //Propertybag DEMC
	PROPERTYBAG_FASTA_PROTEIN_DEMC,
	PROTERTYBAG_TRINOTATE_REPORT_DEMC,
	PROPERTYBAG_DIFFERENTIAL_MATRIX_DEMC,
	PROPTERYBAG_INFERNAL_DEMC,
	PROPERTYBAG_COLUMNS_TO_PARSE_DEMC,
	PROPERTYBAG_BOOL_COLUMNS_DEMC,
	PROPERTYBAG_OUTPUTFOLDER_DEMC,
	PROPERTYBAG_PREFIX_DEMC,
	PROPERTYBAG_BOOL_FASTA_FILTER_DEMC,

	PROPERTYBAG_KEGGMATRIX_KEGGCOUNTER = 660, //Propertybag KEGGCounter
	PROPERTYBAG_KEGGDESCRIPTION_KEGGCOUNTER,
	PROPERTYBAG_BOOL_PREFIXTAG_KEGGCOUNTER,
	PROPERTYBAG_PREFIXTAG_KEGGCOUNTER,
	PROPERTYBAG_THRESHOLD_DE_KEGGCOUNTER,
	PROPERTYBAG_THRESHOLD_HITS_KEGGCOUNTER,
	PROPERTYBAG_THRESHOLD_SETSAVAILABLE_KEGGCOUNTER,
	PROPERTYBAG_OUTPUT_FOLDER_KEGGCOUNTER,

	PROPERTYBAG_FASTAPATH_BAVA = 680, //Propertybag BAVA (Blast All Vs All)
	PROPERTYBAG_BLASTDIR_BAVA,
	PROPERTYBAG_OUTPUTDIR_BAVA,
	PROPERTYBAG_OUTPUTPREFIX_BAVA,
	PROPERTYBAG_EVALUETHRESHOLD_BAVA,
	PROPERTYBAG_PERCENTAGETHRESHOLD_BAVA,	
	PROPERTYBAG_STRAINAMECONVERSION_BAVA,
	PROPERTYBAG_BOOL_MMSEQS_BAVA,

	PROPERTYBAG_PARTITIONFILE_CLCHECK = 700, //Propertybag CLCheck
	PROPERTYBAG_CLIPKITFILE_CLCHECK,
	PROPERTYBAG_OUTPUTDIR_CLCHECK,

	PROPERTYBAG_GETINPUTFOLDER_MIAF = 720, //Propertybag MIAF
	PROPERTYBAG_GETOUTPUTFOLDER_MIAF,
	PROPERTYBAG_GETMAFFTPATH_MIAF,
	PROPERTYBAG_GETIQTREEPATH_MIAF,
	PROPERTYBAG_GETSCRIPTPATH_MIAF,
	PROPERTYBAG_GETSYSTEMTYPE_MIAF,
	PROPERTYBAG_GETCPUTLIMIT_MIAF,
	PROPERTYBAG_GETIQTHREADLIMIT_MIAF,
	PROPERTYBAG_GETJOBTIMELIMIT_MIAF,
	PROPERTYBAG_BOOLPREQUAL_MIAF,
	PROPERTYBAG_BOOL_PREQUAL_IQTREE_MIAF,
	PROPERTYBAG_GETAPPPFPATH_MIAF,
	PROPERTYBAG_BOOL_APPPF_MIAF,
	PROPERTYBAG_TAXONOMICGROUPFILE_MIAF,

	PROPERTYBAG_INPUTFOLDER_FFRBOL = 740, //Propertybag FFRBOL
	PROPERTYBAG_OUTPUTFOLDER_FFRBOL,
	PROPERTYBAG_MINLENGHT_FFRBOL,
	PROPERTYBAG_MAXLENGTH_FFRBOL,

	PROPERTYBAG_PROTEINNAME_CHANGE_GTVO = 760, //Propertybag GTVO
	PROPERTYBAG_COGS_PPP_GTVO,
	PROPERTYBAG_COGS_FPPP_GTVO,
	PROPERTYBAG_ORTHOGROUP_GTVO,
	PROPERTYBAG_OUTPUTFOLDER_GTVO,
	PROPERTYBAG_TAXONOMICGROUP_GTVO,
	PROPERTYBAG_TPM_FOLDER_GTVO,
	PROPERTYBAG_PREFIX_OUTPUT_GTVO,
	PROPERTYBAG_BOOL_PREFIX_GTVO,
	
	FASTA_PUSBACKBLOCK_ADD_VECTOR = 1000, //Fasta Block
	FASTABLOCK_SETBLOCK_NOFASTAFORMAT,
	FASTABLOCK_SETFASTAHEADER,
	FASTABLOCK_SETFASTAHEADERADDON,
	FASTABLOCK_SETFASTAHEADER_POINTERDIFFERENCE,
	FASTABLOCK_SETFASTAHEADERSTRAIN_POINTERDIFFERENCE,
	FASTABLOCK_SETFASTAHEADERADDON_POINTERDIFFERENCE,
	FASTABLOCK_SETHEADERSTRAIN_NODATA,
	FASTABLOCK_SETFASTAHREST_POITNERDIFFERENCE,
	FASTABLOCK_SETHEADERREST_NODATA,
	FASTABLOCK_GETFASTAHEADER,
	FASTABLOCK_SETFASTASEQUENCE,
	FASTABLOCK_SETFASTASEQUENCE_POINTERDIFFERENCE,
	FASTABLOCK_GETFASTASEQUENCE,
	FASTABLOCK_GETFASTAHEADERADDON,
	FASTABLOCK_GETHEADERNUMBER,
	FASTABLOCK_GETHEADERSTRAIN,
	FASTABLOCK_GETHEADERREST, ////
	FASTABLOCK_SETHEADERNUMBER,
	FASTABLOCK_GETWRITEFASTABLOCKBOOL,
	FASTABLOCK_SETWRITEFASTABLOCKBOOL,
	FASTABLOCK_SETFASTAHEADERADDONBOOL,
	FASTABLOCK_SETKEGGMATRIXBOOL,
	FASTABLOCK_GETKEGGMATRIXBOOL,
	FASTABLOCK_SETKEGGMATRIX,
	FASTABLOCK_GETKEGGMATRIX,

	FASTAFILE_GETFASTAFILEBUFFER = 1500, //Fasta File
	FASTAFILE_WRONGFORMAT,
	FASTAFILE_PARSEFASTABLOCK_WRONGFORMAT,
	FASTAFILE_SETFASTAFILENAME_POINTERDIFFERENCE,
	FASTAFILE_GETFASTAFILENAME,
	FASTAFILE_EMPTY_STRING_FASTAFILENAME,
	FASTAFILE_MATCHING_FASTABLOCK_NOT_FOUND,
	FASTAFILE_MATCHING_FASTABLOCK_NOT_FOUND_BASED_ON_HEADERNUMBER,
	FASTAFILE_SETMATCHINGNAME_POINTERDIFFERENCE,
	FASTAFILE_EMPTY_STRING_MATCHINGNAME,
	FASTAFILE_GETMATCHINGNAME,

	TABLEROW_SETCOLUMNNAME_HEADER = 2000, //Table Row
	TABLEROW_SETCOLUMNNAMENEW_HEADER,
	TABLEROW_SETCOLUMNNAMENEW_HEADER_POINTER,
	TABLEROW_GETCOLUMNNAME_HEADER,
	TABLEROW_GETCOLUMNNAMENEW_HEADER,

	TABLE_NOTMATCHING_COLUMNNUMBER = 2500, //Whole Table
	TABLE_NOMATCH_HEADERCOLUMN,
	TABLE_NEWNAME_SIZE_FORMAT_WRONG,
	TABLE_PARSE_ROW_SIZE_TOO_SMALL,
	TABLE_PARSE_ROW_SIZE_TOO_BIG,
	TABLE_NEWCOLUMN_SIZE_FORMAT_WRONG,
	TABLE_PARSE_ROW_SIZE_FORMAT_WRONG,
	TABLE_SIZE_HEADER_COLUMN_WRONG,
	TABLE_FIND_MATCHING_ROW_NAME_DOES_NOT_EXIST,
	TABLE_ROW_MATCHING_NOT_FOUND,
	TABLE_PARSE_HEADER_FORMAT_WRONG,
	TABLE_HEADER_VECTOR_AND_COLUMN_COUNT_NOT_MATCHING,
	TABLE_PARSE_TABLE_FORMAT_WRONG_NO_EOL,
	TABLE_CREATE_FILE_BUFFER,
	TABLE_SET_TABLE_ROW_HEADER,
	TABLE_GET_TABLE_ROW_HEADER,
	TABLE_NO_TABLE_CONTENT,
	TABLE_GET_TABLE_NAME,
	TABLE_PUSHBACK_ROW_SAFE,
	TABLE_PUSHBACK_NO_ROWS,
	TABLE_POPBACK_NO_ROWS,
	TABLE_FIND_TABLE_IN_TABLE_VECTOR_DOES_NOT_EXIST,
	TABLE_FIND_TABLE_TABLE_QUERY_VARIABLE_EMPTY,
	TABLE_STRING_TO_CLEAR_ROW_AND_COLUMN_EMPTY,
	TABLE_REPLACE_COLUMN_NEW_COLUMN_EMPTY,



	TAXONOMIC_GROUP_FIND_SPECIES_SPECIESNAME = 3000,
	TAXONOMIC_GROUP_FIND_SPECIES_HEADERNAME,

	INFERNAL_SET_ISOFORMID_SZ = 3500,
	INFERNAL_SET_ISOFORMID_SIZE,
	INFERNAL_SETISOFORMID_POINTERDIFFERENCE,
	INFERNAL_SET_ACCESSION_SZ,
	INFERNAL_SET_ACCESSION_SIZE,
	INFERNAL_SETACCESSION_POINTERDIFFERENCE,
	INFERNAL_SET_DESCRIPTION_SZ,
	INFERNAL_SET_DESCRIPTION_SIZE,
	INFERNAL_SETDESCRIPTION_POINTERDIFFERENCE,
	INFERNAL_GETISOFORMID,
	INFERNAL_GETACCESSION,
	INFERNAL_GETDESCRIPTION,

	DIFFERENTIALMATRIX_SET_ROW_DEMATRIX_EMPTY = 4000,
	DIFFERENTIALMATRIX_SET_ROW_TRINOTATE_EMPTY,
	DIFFERENTIALMATRIX_SET_TRINITY_EMPTY,
	DIFFERENTIALMATRIX_SET_PROTEIN_EMPTY,
	DIFFERENTIALMATRIX_SET_INFERNAL_EMPTY,
	DIFFERENTIALMATRIX_GET_ROW_DEMATRIX_EMPTY,
	DIFFERENTIALMATRIX_GET_ROW_TRINOTATE_EMPTY,
	DIFFERENTIALMATRIX_GET_TRINITY_EMPTY,
	DIFFERENTIALMATRIX_GET_PROTEIN_EMPTY,
	DIFFERENTIALMATRIX_GET_INFERNAL_EMPTY,


	JOB_SETINPUTFILE_STRING_RASFAF = 4500, // JOBS class in RASFAF
	JOB_SETINPUTFILE_POSITION_RASFAF,
	JOB_GETINPUTFILE_RASFAF,
	JOB_SETOUTPUTFILE_STRING_RASFAF,
	JOB_SETOUTPUTFILE_POSITION_RASFAF,
	JOB_GETOUTPUTFILE_RASFAF,
	JOB_SETSYSTEMCOMMAND_STRING_RASFAF,
	JOB_SETSYSTEMCOMMAND_POSITION_RASFAF,
	JOB_GETSYSTEMCOMMAND_RASFAF,
	JOB_FINDEMPTYSPOT_FORNEWJOB_RASFAF,
	JOB_ALREADYFINISHED_RASFAF,
	JOB_EMPTYJOBOBJECT,
	JOB_NOTFINISHEDYET_RASFAF,
	JOB_NOEMPTYSPOTFOUND_RASFAF,

	KEGGSET_KEGGID_DOES_NOT_EXIST = 5000, //Class functions CKEGGSet
	KEGGSET_KEGGID_NOT_FILLED,
	KEGGSET_KEGGID_GET_FAIL,
	KEGGSET_COUNTERINCREASE_NOT_VALID,
	KEGGSET_KEGGSETTHRESHOLD_NOT_VALID,
	KEGGSET_SETKEGGROW_KEGGROW_NOT_VALID,
	KEGGSET_KEGGSET_NOT_FOUND_VECTOR,

	NAMEDMAPS_SETMAPNAME_POINTERDIFFERENCE = 5500, //Class Named Maps
	NAMEDMAPS_EMPTY_STRING_MAPNAME,
	NAMEDMAPS_GETMAPNAME,
	NAMEDMAPS_EMPTYMAP,
	NAMEDMAPS_EMPTYKEY,
	NAMEDMAPS_MATCHING_NAMEDMAPFILE_NOT_FOUND,

	JOB_SETFASTAFILEPATH_POSITION_MIAF = 6000, //Class functions CJOBS for MIAF and process functions for MIAF
	JOB_GETFASTAFILEPATH_MIAF,
	JOB_SETINPUTFILENAME_POSITION_MIAF,
	JOB_GETFASTAFILENAME_MIAF,
	JOB_TIMELIMIT_REACHED_MIAF,
	JOB_CANT_RUN_NOIQTREE_PATH,

	PARSEINPUT_FILE_BLAST_NO_ROWS = 10000, //own ones - Input function/ GPDS
	PARSEINPUT_FILE_BLAST_NO_TABLE,
	PARSEINPUT_FILE_BLAST_NO_TABLENAME,
	PARSEINPUT_FILE_SPLIT_FASTA_FILES_NO_FASTABLOCKS,

	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_SET_SPECIESNAME = 10200, //Own ones - input function / OSG
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_SET_SPECIESNAME_SIZETOSMALL,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_GET_SPECIESNAME,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_SET_HEADERNAME,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_SET_HEADERNAME_SIZETOSMALL,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICSPECIES_GET_HEADERNAME,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_TAXONOMICGROUP_PUSHBACK_TAXONOMIC_SPECIES,
	PARSE_INPUT_FILE_TAXONOMICGROUPFILE_WRONG_FORMAT,

	PARSE_INPUT_FILE_HEADERFILE_SETFILEBUFFER_RFBS = 10300, //Own ones - Input Functon / RFBS
	PARSE_INPUT_FILE_HEADERFILE_WRONG_FORMAT_RFBS,

	MATCHING_FASTAFILE_NOT_FOUND = 11000, //Matching Function
	MATCHING_SPLIT_HEADERNAME_AND_NUMBER_TOO_SMALL,

	MATCHING_FASTAFILE_FILENAME_NOT_FOUND = 11100,
	MATCHING_FASTAFILE_MATCHINGNAME_NOT_FOUND,

	MATCHING_FASTAFILE_DOES_NOT_EXIST_RFBS = 11200,
	MATCHING_HEADERNAME_DOES_NOT_EXIST_RFBS,
	MATCHING_HEADERNAME_HEADERORSTRAIN_DOES_NOT_EXIST_RFBS,
	MATCHING_HEADERNAME_WRONG_FORMAT,

	DEMC_MATCHING_INFERNAL_NOT_FOUND = 11300,
	DEMC_SPLIT_DE_NAMES_EMPTY_COLUMN_NAME,
	DEMC_SPLIT_DE_NAMES_COLUMN_NOT_FOUND,
	DEMC_PROTEIN_DESCRIPTION_NOT_FOUND,


	PARSE_INPUT_FILE_PARTITION_FILE_ALIGNMENT_SIZE_NOT_THE_SAME_CLCHECK = 11400,
	PARSE_INPUT_FILE_PARTITION_FILE_PARSEDPARITIONFILE_VECTOR_NOT_SAME_ALIGNMENT_SIZE_CLCHECK,

	GTVO_HEADER_CREATION_SPECIES_NAME_EMPTY = 11500, //GTVO


	WRITE_OUTPUT_FILE_ERROR_FOPEN = 70000, //Write output function //Process Files
	WRITE_OUTPUT_FILE_SUMMARY_DECONTAMINATION,
	REPLACE_STRING_FOR_SZOBJECT_ZERO_STRING_SIZE,
	DUPLICATE_ZERO_TERMINATED_STRING_SIZE_ZERO,

	WRITE_OUTPUT_ORTHOGROUP_FASTAOBJECT = 70200, //Write Output Function no fasta file object
	WRITE_OUTPUT_FILE_SUMMARY_OSG,

	FILTERED_DIR_LIST = 99999, //Failed Dir list
	FILTERED_DIR_LIST_NO_ITEMS, //No items in dir list.

};

class CManagement
{
public:
	CManagement() {};
	~CManagement() {};
	virtual const char* GetErrorDescription(long lError) const;
	long ErrorChecker(long lError) const;
};